import psycopg2 
import os
from dotenv import load_dotenv

load_dotenv()

CONNECTION_STRING = os.getenv('CONNECTION_STRING')
conn = psycopg2.connect(CONNECTION_STRING)

cur = conn.cursor()

cur.execute("""
CREATE TABLE IF NOT EXISTS PATIENT DETAILS (
    ID SERIAL PRIMARY KEY,
    GENDER CHAR,
    NAME VARCHAR(20),
    DATE VARCHAR(6),
    BEDNO INTEGER
)           
""")

cur.execute("""
CREATE TABLE IF NOT EXISTS ECG (
    ID SERIAL PRIMARY KEY,
    PID INTEGER NOT NULL,
    RECORDED_AT TIMESTAMP NOT NULL,

    LEAD_STATUS INTEGER,
    HRV INTEGER,
    ARR_TYPE INTEGER,
            
    FOREIGN KEY (PID)
        REFERENCES patient(ID)
        ON DELETE CASCADE
)
""")

cur.execute("""
CREATE TABLE IF NOT EXISTS ECG_WAVEFORM (
    WAVE_ID SERIAL PRIMARY KEY,
    ECG_ID INTEGER NOT NULL,
    LEAD_STATUS INTEGER,
    RECORDED_AT TIMESTAMP NOT NULL,
            
    WAVE1 INTEGER[],
    WAVE2 INTEGER[],
    WAVEV INTEGER[],

    FOREIGN KEY (ECG_ID)
        REFERENCES ECG(ID)
        ON DELETE CASCADE
)
""")

cur.execute("""
CREATE TABLE IF NOT EXISTS RESP (
    ID SERIAL PRIMARY KEY,
    PID INTEGER NOT NULL, 
    RECORDED_AT TIMESTAMP NOT NULL,

    RESP_RATE INTEGER,
            
    FOREIGN KEY (PID)
        REFERENCES patient(ID)
        ON DELETE CASCADE
)
""")

cur.execute("""
CREATE TABLE IF NOT EXISTS RESP_WAVEFORM (
    WAVE_ID SERIAL PRIMARY KEY,
    RESP_ID INTEGER NOT NULL,
    RECORDED_AT TIMESTAMP NOT NULL,
            
    WAVEFORM INTEGER[],

    FOREIGN KEY (RESP_ID)
        REFERENCES RESP(ID)
        ON DELETE CASCADE
)
""")

cur.execute("""
CREATE TABLE IF NOT EXISTS SPO2 (
    ID SERIAL PRIMARY KEY,
    PID INTEGER NOT NULL,
    RECORDED_AT TIMESTAMP NOT NULL,

    SPO2_VALUE INTEGER,
    PULSE_RATE INTEGER,
    ERROR_MSG INTEGER,
            
    FOREIGN KEY (PID)
        REFERENCES patient(ID)
        ON DELETE CASCADE
)
""")

cur.execute("""
CREATE TABLE IF NOT EXISTS SPO2_WAVEFORM (
    WAVE_ID SERIAL PRIMARY KEY,
    SPO2_ID INTEGER NOT NULL,
    RECORDED_AT TIMESTAMP NOT NULL,
            
    WAVEFORM INTEGER[],

    FOREIGN KEY (SPO2_ID)
        REFERENCES SPO2(ID)
        ON DELETE CASCADE      
)
""")

cur.execute("""
CREATE TABLE IF NOT EXISTS TEMP (
    ID SERIAL PRIMARY KEY,
    PID INTEGER NOT NULL,
    RECORDED_AT TIMESTAMP NOT NULL,

    LEAD_STATUS INTEGER,
    TEMP1 FLOAT,
    TEMP2 FLOAT,
            
    FOREIGN KEY (PID)
        REFERENCES patient(ID)
        ON DELETE CASCADE
)
""")

cur.execute("""
CREATE TABLE IF NOT EXISTS NIBP (
    ID SERIAL PRIMARY KEY,
    RECORDED_AT TIMESTAMP NOT NULL,

    SYS INTEGER,
    MAP INTEGER,
    DIA INTEGER,
    ERROR_MSG INTEGER,
            
    FOREIGN KEY (PID)
        REFERENCES patient(ID)
        ON DELETE CASCADE
)
""")

conn.commit()
cur.close()
conn.close()